### ISSUE TITLE
Warlock - All specs with broken spells

### ISSUE THREAD

**Issue by SyntaxHell** [MagicStormTeam/MagicStormTeam-Legion#1]
**General:**

Healthstone
[ItemID: 5512] - Restores very very little HP (about 2,5%) when it should restore 25% of total HP

Summon Infernal
[SpellID: 1122] - Doesn't attack the target if you haven't attacked it first, if you summon it and then attack a target the Infernal will not do anything

Summon Infernal
[SpellID: 18540] - Doesn't attack any target, doesn't matter if you attacked first or not

Command Demon
[SpellID: 119898] - Doesn't do anything, you cannot click on any of your demons

--TALENTS--

Demonic Circle
[SpellID: 48018] - Works fine, but doesn't show cooldown when you can teleport

Grimoire of Synergy
[TalentID: 21717] - Never procs, broken

Soul Conduit
[TalentID: 19293] - Refunds WHOLE gems instead of shards, but only after you cast a spell that generates shards

Empowered Life Tap
[TalentID: 22088]- Doesn't increase the damage done

**Pets:**

Summon Felguard
[SpellID: 30146] - Has no energy making it unable to cast spells

**Destruction:**

--SPELLS--

Immolate 
[SpellID: 348] - The spell generates a WHOLE gem instead of one shard per tick

Havoc
[SpellID: 80240] - Applies to target but doesn't do anything

Conflagrate
[SpellID: 17962] - The spell generates five WHOLE gems instead of 5 shards

--TALENTS--

Shadowburn
[TalentID: 22052] - Doesn't generate any shards or gems

Eradication
[TalentID: 21695] - Doesn't increase the damage done to target after a Chaos Bolt on target

Channel Demonfire
[TalentID: 22482] - Doesn't work, cannot use spell at all

**Affliction:**

--SPELLS--

Agony
[SpellID: 172] - Generates a WHOLE gem instead of shard and does too little damage

Seed of Corruption
[SpellID: 27243] - Doesn't refund a shard when target dies

Unstable Affliction
[SpellID: 30108] - Refunds a WHOLE gem instead of a shard when target dies

Drain Soul
[SpellID: 198590]  - Refunds a WHOLE gem instead of a shard when target dies

--TALENTS--

Contagion
[TalentID: 22044] - Doesn't increase the damage done to target

Siphon Life
[TalentID: 19281] - Doesn't heal you

**Demonology:**

--SPELLS--

Shadow Bolt
[SpellID: 686] - The spell generates a WHOLE gem instead of one shard

Call Dreadstalkers
[SpellID: 104316] - They spawn but doesn't do anything, they just stand there

Hand of Gul'Dan
[SpellID: 105174] - Doesn't summon any Wild Imps

Demonwrath
[SpellID: 193440] - Doesn't deal any damage

--TALENTS--

Impending Doom
[TalentID: 22045] - Doesn't summon Wild Imp at the end

Improved Dreadstalkers
[TalentID: 21694] - Doesn't summon Wild Imps

Implosion
[TalentID: 22089] - Doens't do anything, since there is no Wild Imps

Power Trip
[TalentID: 22042] - Generates a WHOLE gem instead of shard

**Comment by welder1976** [comment]
![image](https://user-images.githubusercontent.com/17787377/52481559-e0b1b000-2bbf-11e9-905d-48dfa7e19790.png)
work

**Comment by SyntaxHell** [comment]
I am closing this issue and I will make one issue per spell.
